"""First revision

Revision ID: ee59dc00831a
Revises:
Create Date: 2025-07-14 16:19:33.698900

"""

from typing import Sequence, Union
import enum

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ee59dc00831a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Define enums needed for the migration
class Gender(str, enum.Enum):
    """Enumeration"""

    MALE = "male"
    FEMALE = "female"


class TeachingMethod(str, enum.Enum):
    """Enumeration of teaching methods."""

    ONLINE = "online"
    IN_PERSON = "in person"
    HYBRID = "hybrid"


class EducationLevel(str, enum.Enum):
    """Enumeration of education levels."""

    PRIMARY = "primary"
    SECONDARY = "secondary"
    UNIVERSITY = "university"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create users table
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )

    # Create profiles table
    op.create_table(
        "profiles",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("profile_picture", sa.String(), nullable=True),
        sa.Column("bio", sa.String(), nullable=False),
        sa.Column("degrees", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("years_of_experience", sa.String(), nullable=True),
        sa.Column("subjects", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("levels", postgresql.ARRAY(sa.Enum(EducationLevel)), nullable=True),
        sa.Column("teaching_method", sa.Enum(TeachingMethod), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("gender", sa.Enum(Gender), nullable=False, server_default="male"),
        sa.Column("hourly_rate", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), nullable=False, server_default="TND"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profiles")
    op.drop_table("users")
    # ### end Alembic commands ###
